@startuml SD

actor "User" as User
participant "View" as View
participant "Controller" as Controller
participant "Service" as Service

title Sequence Diagram: Sửa thông tin bài hát

autonumber

User -> View: User chọn chức năng Sửa thông tin bài hát
activate View
View --> View: Hiển thị form sửa thông tin bài hát
View -> Controller: Yêu cầu thông tin bài hát cần sửa
activate Controller
Controller -> Service: Yêu cầu thông tin bài hát
activate Service
Service --> Controller: Trả về thông tin bài hát
deactivate Service
Controller --> View: Trả về thông tin bài hát trên form
deactivate Controller
View --> View: Hiển thị thông tin bài hát trên form
User -> View: Nhập thông tin mới cho bài hát
View --> View: Kiểm tra thông tin bài hát
View -> Controller: Gửi yêu cầu sửa thông tin bài hát
activate Controller
Controller -> Service: Xử lý yêu cầu sửa thông tin bài hát
activate Service
Service --> Controller: Trả về kết quả sửa thông tin bài hát
deactivate Service
alt Sửa thông tin bài hát thành công
    Controller --> View: Thông báo "Sửa thông tin bài hát thành công"
    View --> View: Tắt form sửa thông tin bài hát
    View --> View: Cập nhật thông tin bài hát mới
else Sửa thông tin bài hát thất bại
    Controller --> View: Thông báo "Sửa thông tin bài hát thất bại, vui lòng thử lại"
end
deactivate Controller
View --> User: Hiển thị thông báo
deactivate View
@enduml