@startuml SD

actor "User" as User
participant "View" as View
participant "Controller" as Controller
participant "Service" as Service

title Sequence Diagram: Sửa thông tin Playlist

autonumber

User -> View: User chọn chức năng Sửa thông tin Playlist
activate View
View --> View: Hiển thị form sửa thông tin Playlist
View -> Controller: Yêu cầu thông tin Playlist cần sửa
activate Controller
Controller -> Service: Yêu cầu thông tin Playlist
activate Service
Service --> Controller: Trả về thông tin Playlist
deactivate Service
Controller --> View: Trả về thông tin Playlist trên form
deactivate Controller
View --> View: Hiển thị thông tin Playlist trên form
User -> View: Nhập thông tin mới cho Playlist
View --> View: Kiểm tra thông tin Playlist
View -> Controller: Gửi yêu cầu sửa thông tin Playlist
activate Controller
Controller -> Service: Xử lý yêu cầu sửa thông tin Playlist
activate Service
Service --> Controller: Trả về kết quả sửa thông tin Playlist
deactivate Service
alt Sửa thông tin Playlist thành công
    Controller --> View: Thông báo "Sửa thông tin Playlist thành công"
    View --> View: Tắt form sửa thông tin Playlist
    View --> View: Cập nhật thông tin Playlist mới
else Sửa thông tin Playlist thất bại
    Controller --> View: Thông báo "Sửa thông tin Playlist thất bại, vui lòng thử lại"
end
deactivate Controller
View --> User: Hiển thị thông báo
deactivate View
@enduml