@startuml SD

actor "User" as User
participant "View" as View
participant "Controller" as Controller
participant "Service" as Service

title Sequence Diagram: Sửa hồ sơ cá nhân

autonumber

User -> View: User chọn chức năng Sửa hồ sơ cá nhân
activate View
View --> View: Hiển thị form sửa thông tin hồ sơ cá nhân
View -> Controller: Yêu cầu thông tin hồ sơ cá nhân cần sửa
activate Controller
Controller -> Service: Yêu cầu thông tin hồ sơ cá nhân
activate Service
Service --> Controller: Trả về thông tin hồ sơ cá nhân
deactivate Service
Controller --> View: Trả về thông tin hồ sơ cá nhân trên form
deactivate Controller
View --> View: Hiển thị thông tin hồ sơ cá nhân trên form
User -> View: Nhập thông tin mới cho hồ sơ
View --> View: Kiểm tra thông tin nhập
View -> Controller: Gửi yêu cầu sửa thông tin hồ sơ cá nhân
activate Controller
Controller -> Service: Xử lý yêu cầu sửa thông tin hồ sơ cá nhân
activate Service
Service --> Controller: Trả về kết quả sửa thông tin hồ sơ cá nhân
deactivate Service
alt Sửa thông tin thành công
    Controller --> View: Thông báo "Sửa thông tin hồ sơ cá nhân thành công"
    View --> View: Tắt form sửa thông tin hồ sơ cá nhân
    View --> View: Cập nhật hồ sơ cá nhân mới
else Sửa thông tin thất bại
    Controller --> View: Thông báo "Sửa thông tin hồ sơ cá nhân thất bại, vui lòng thử lại"
end
deactivate Controller
View --> User: Hiển thị thông báo
deactivate View
@enduml