@startuml SD

actor "User" as User
participant "View" as View
participant "Controller" as Controller
participant "Service" as Service

title Sequence Diagram: Nghe nhạc

autonumber

User -> View: User chọn chức năng Nghe nhạc
activate View
View -> Controller: Yêu cầu phát bài hát
activate Controller
Controller -> Service: Yêu cầu phát bài hát
activate Service
Service --> Controller: Trả về kết quả phát bài hát
alt Phát bài hát thành công
    Controller --> View: Hiển thị bài hát và trạng thái phát
else Phát bài hát thất bại
    Controller --> View: Thông báo "Phát nhạc thất bại, vui lòng thử lại"
end
deactivate Controller
deactivate Service

User -> View: Chọn chức năng Phát/Tạm dừng
View -> Controller: Yêu cầu cập nhật trạng thái phát nhạc
activate Controller
Controller -> Service: Yêu cầu cập nhật trạng thái phát nhạc
activate Service
Service --> Controller: Trả về kết quả cập nhật trạng thái
deactivate Service
deactivate Controller
Controller --> View: Cập nhật trạng thái phát nhạc

User -> View: Chọn chức năng Bài tiếp theo/Trước đó
View -> Controller: Yêu cầu chuyển bài hát
activate Controller
Controller -> Service: Yêu cầu chuyển bài hát
activate Service
Service --> Controller: Trả về bài hát mới
deactivate Service
deactivate Controller
Controller --> View: Hiển thị bài hát mới
deactivate View
@enduml