@startuml SD

actor "User" as User
participant "View" as View
participant "Controller" as Controller
participant "Service" as Service

title Sequence Diagram: Đăng Nhập

autonumber

User -> View: User chọn chức năng Đăng Nhập
activate View
View --> View: Hiển thị form đăng nhập
User -> View: Nhập thông tin đăng nhập
View --> View: Kiểm tra thông tin đăng nhập
alt Thông tin không hợp lệ
    View --> View: Thông báo "Thông tin không hợp lệ, vui lòng thử lại"
else Thông tin hợp lệ
    View -> Controller: Yêu cầu đăng nhập
    activate Controller
    Controller -> Service: Yêu cầu đăng nhập
    activate Service
    Service --> Service: Xử lý đăng nhập
    Service --> Controller: Trả về kết quả đăng nhập
    deactivate Service
    alt Đăng nhập thành công
        Controller --> View: Thông báo "Đăng nhập thành công"
        View --> View: Tắt form đăng nhập
        View --> User: Hiển thị thông báo
        View --> User: Chuyển sang giao diện Chính
    else Đăng nhập thất bại
        Controller --> View: Thông báo "Sai email hoặc mật khẩu, vui lòng thử lại"
        View --> User: Hiển thị thông báo
    end
    deactivate Controller
end

deactivate View
@enduml