@startuml SD

actor "User" as User
participant "View" as View
participant "Controller" as Controller
participant "Service" as Service

title Sequence Diagram: Đăng Xuất

autonumber

User -> View: User chọn chức năng Đăng Xuất
activate View
View -> Controller: Gửi yêu cầu đăng xuất
activate Controller
Controller -> Service: Xử lý yêu cầu đăng xuất
activate Service
Service --> Controller: Trả về kết quả đăng xuất
deactivate Service
Controller --> View: Thông báo "Đăng xuất thành công"
deactivate Controller
View --> View: Chuyển sang giao diện Khách
deactivate View
@enduml