@startuml SD

actor "Admin" as Admin
participant "View" as View
participant "Controller" as Controller
participant "Service" as Service
participant "User" as User

title Sequence Diagram: Quản lý báo cáo vi phạm

autonumber

Admin -> View: Admin chọn chức năng Quản lý báo cáo vi phạm
activate View
View -> Controller: Yêu cầu danh sách báo cáo vi phạm
activate Controller
Controller -> Service: Yêu cầu danh sách báo cáo vi phạm
activate Service
Service --> Controller: Trả về danh sách báo cáo vi phạm
deactivate Service
Controller --> View: Trả về danh sách báo cáo vi phạm
deactivate Controller
View --> View: Hiển thị danh sách báo cáo vi phạm

Admin -> View: Xem báo cáo vi phạm và chọn phương thức xử lý
View -> Controller: Yêu cầu xử lý báo cáo vi phạm
activate Controller
Controller -> Service: Yêu cầu xử lý báo cáo vi phạm
activate Service

alt Xử lý thất bại
    Service --> Controller: Trả về kết quả xử lý báo cáo thất bại
    Controller --> View: Thông báo "Xử lý báo cáo thất bại, vui lòng thử lại"
    View --> Admin: Hiển thị thông báo
else Xử lý thành công
    Service -> User: Gửi thông báo kết quả xử lý báo cáo
    Service --> Controller: Trả về kết quả xử lý báo cáo thành công
    deactivate Service
    Controller --> View: Thông báo "Xử lý báo cáo thành công"
    deactivate Controller
    View --> View: Cập nhật danh sách báo cáo vi phạm
    View --> Admin: Hiển thị thông báo
end
deactivate View
@enduml