@startuml SD

actor "Admin" as Admin
participant "View" as View
participant "Controller" as Controller
participant "Service" as Service

title Sequence Diagram: Quản lý tài khoản người dùng

autonumber

Admin -> View: Admin chọn chức năng Quản lý tài khoản người dùng
activate View
View -> Controller: Yêu cầu danh sách tài khoản
activate Controller
Controller -> Service: Yêu cầu danh sách tài khoản
activate Service
Service --> Controller: Trả về danh sách tài khoản
deactivate Service
Controller --> View: Trả về danh sách tài khoản
deactivate Controller
View --> View: Hiển thị danh sách tài khoản

Admin -> View: Chọn tài khoản để Khoá/Mở
View -> Controller: Yêu cầu cập nhật trạng thái tài khoản
activate Controller
Controller -> Service: Yêu cầu cập nhật trạng thái tài khoản
activate Service
Service --> Controller: Trả về kết quả cập nhật trạng thái tài khoản
deactivate Service
Controller --> View: Thông báo kết quả cập nhật trạng thái tài khoản
deactivate Controller
View --> Admin: Hiển thị thông báo
deactivate View
@enduml