@startuml SD

actor "User" as User
participant "View" as View
participant "Controller" as Controller
participant "Service" as Service

title Sequence Diagram: Quản lý hồ sơ cá nhân

autonumber

User -> View: User chọn chức năng Quản lý hồ sơ cá nhân
activate View
View -> Controller: Yêu cầu hồ sơ cá nhân
activate Controller
Controller -> Service: Yêu cầu hồ sơ cá nhân
activate Service
Service --> Controller: Trả về hồ sơ cá nhân
deactivate Service
Controller --> View: Trả về hồ sơ cá nhân
deactivate Controller
View --> View: Hiển thị hồ sơ cá nhân

User -> View: Chọn chức năng Sửa hồ sơ cá nhân (Chuyển sang Usecase Sửa hồ sơ cá nhân)
User -> View: Chọn chức năng Xem danh sách bài hát đăng lại (Chuyển sang Usecase Xem danh sách và tìm kiếm bài hát đăng lại)

deactivate View
@enduml