@startuml SD

actor "User" as User
participant "View" as View
participant "Controller" as Controller
participant "Service" as Service

title Sequence Diagram: Quản lý Playlist cá nhân

autonumber

User -> View: User chọn chức năng Quản lý Playlist cá nhân
activate View
View -> Controller: Yêu cầu danh sách Playlist
activate Controller
Controller -> Service: Yêu cầu danh sách Playlist
activate Service
Service --> Controller: Trả về danh sách Playlist
deactivate Service
Controller --> View: Trả về danh sách Playlist
deactivate Controller
View --> View: Hiển thị danh sách Playlist

User -> View: Chọn chức năng Tạo Playlist cá nhân (Chuyển sang Usecase Tạo Playlist cá nhân)
User -> View: Chọn chức năng Quản lý chi tiết Playlist cá nhân (Chuyển sang Usecase Sửa thông tin Playlist cá nhân)

User -> View: Chọn 1 Playlist và nhấn Xoá
View -> Controller: Yêu cầu xoá Playlist
activate Controller
Controller -> Service: Yêu cầu xoá Playlist
activate Service
Service --> Controller: Trả về kết quả xoá Playlist
deactivate Service
alt Xoá Playlist thành công
    Controller --> View: Thông báo "Xoá Playlist thành công"
else Xoá Playlist thất bại
    Controller --> View: Thông báo "Xoá Playlist thất bại, vui lòng thử lại"
end
deactivate Controller
View --> User: Hiển thị thông báo
deactivate View
@enduml