@startuml SD

actor "User" as User
participant "View" as View
participant "Controller" as Controller
participant "Service" as Service

title Sequence Diagram: Quản lý bài hát cá nhân

autonumber

User -> View: User chọn chức năng Quản lý bài hát cá nhân
activate View
View -> Controller: Yêu cầu danh sách bài hát
activate Controller
Controller -> Service: Yêu cầu danh sách bài hát
activate Service
Service --> Controller: Trả về danh sách bài hát
Controller --> View: Hiển thị danh sách bài hát
deactivate Controller
deactivate Service

User -> View: Chọn chức năng Tải lên bài hát(Chuyển sang Usecase Tải lên bài hát)
User -> View: Chọn chức năng Sửa thông tin bài hát(Chuyển sang Usecase Sửa thông tin bài hát)

User -> View: Chọn chức năng Ẩn/Hiện bài hát
View -> Controller: Yêu cầu cập nhật trạng thái bài hát
activate Controller
Controller -> Service: Yêu cầu cập nhật trạng thái bài hát
activate Service
Service --> Controller: Trả về kết quả cập nhật trạng thái bài hát
deactivate Service
alt Cập nhật trạng thái bài hát thành công
Controller --> View: Thông báo "Cập nhật trạng thái thành công"
View --> View: Cập nhật danh sách bài hát
else Cập nhật trạng thái bài hát thất bại
Controller --> View: Thông báo "Cập nhật trạng thái thất bại, vui lòng thử lại"
end
deactivate Controller

deactivate View
@enduml