@startuml SD

actor "User" as User
participant "View" as View
participant "Controller" as Controller
participant "Service" as Service

title Sequence Diagram: Báo cáo vi phạm

autonumber

User -> View: User chọn chức năng Báo cáo vi phạm
activate View
View --> View: Hiển thị form thông tin báo cáo

User -> View: Nhập thông tin báo cáo
View --> View: Kiểm tra thông tin báo cáo
View -> Controller: Gửi yêu cầu nhận báo cáo
activate Controller
Controller -> Service: Lưu báo cáo
activate Service
Service --> Controller: Trả về kết quả lưu báo cáo
deactivate Service
alt Lưu báo cáo thành công
    Controller --> View: Thông báo "Báo cáo thành công"
    View --> View: Tắt form thông tin báo cáo
else Lưu báo cáo thất bại
    Controller --> View: Thông báo "Báo cáo thất bại, vui lòng thử lại"
end
deactivate Controller
View --> User: Hiển thị thông báo
deactivate View
@enduml