@startuml Sequence Diagram - Xem Danh Sách Và Tìm Kiếm Nghệ Sĩ 

title Sơ Đồ Tuần Tự - Xem Danh Sách Và Tìm Kiếm Nghệ Sĩ 

actor "Người dùng" as User
participant ":NextJS Client" as UI
participant ":SearchController" as Controller
participant ":SearchService" as Service
participant ":ArtistRepository" as DB

autonumber

' === BƯỚC 1: TẢI DANH SÁCH BAN ĐẦU ===
User -> UI: Vào trang "Tìm kiếm nghệ sĩ"
activate UI

' Gửi request (Chỉ gửi 1 lần)
UI -> Controller: getArtists()
activate Controller
Controller -> Service: getArtists()
activate Service

' Truy vấn DB
Service -> DB: find({ take: 20 })
activate DB
DB --> Service: result
deactivate DB

' Phân nhánh kết quả trả về
alt 1.1: Lỗi kết nối DB / Timeout
    Service --> Controller: Throw InternalServerError
    Controller --> UI: {status: 500, error: "Load Failed"}
    UI --> User: Thông báo "Hiện danh sách thất bại"

else 1: Thành công
    Service --> Controller: {data: artistList}
    deactivate Service
    Controller --> UI: {status: 200, data: artistList}
    deactivate Controller
    UI --> User: Hiển thị danh sách nghệ sĩ
    deactivate UI
end

' === BƯỚC 2: TÌM KIẾM ===
User -> UI: Nhập từ khóa (VD: "Sơn Tùng")
activate UI

' NestJS: Dùng Query Param (?q=keyword)
UI -> Controller: searchArtists(keyword)
activate Controller
Controller -> Service: searchArtists(keyword)
activate Service

' TypeORM: Dùng ILIKE để tìm kiếm không phân biệt hoa thường
Service -> DB: find({ where: { name: ILike(%keyword%) } })
activate DB
DB --> Service: [searchResults]
deactivate DB

Service --> Controller: {data: searchResults}
deactivate Service
Controller --> UI: {status: 200, data: searchResults}
deactivate Controller

UI --> User: Cập nhật danh sách theo kết quả tìm kiếm

' === BƯỚC 3: CHỌN NGHỆ SĨ ===
User -> UI: Chọn Nghệ sĩ -> Chuyển hướng
note right: Hệ thống sẵn sàng cho UC "Theo dõi Nghệ sĩ"(Chuyển user đến trang chi tiết hoặc hiện nút Follow)
deactivate UI

@enduml