@startuml Sơ Đồ Usecase Chi Tiết Admin
left to right direction

' Actor
actor "Quản trị viên" as Admin

rectangle "Quản lý tài khoản người dùng" {
    ' Use Case cho mọi người (chưa đăng nhập)
    (Đăng nhập) as UC_Login

    ' Use case của Admin
    (Quản lý tài khoản người dùng) as UC_ManageUserAccount
    (Xem danh sách và tìm kiếm tài khoản người dùng) as UC_ViewSearchUserAccount
    (Khoá/Mở tài khoản người dùng) as UC_LockUserAccount

    ' -- Mối quan hệ --
    ' Quan hệ <<extend>>
    ' Quản lý tài khoản người dùng
    UC_ViewSearchUserAccount ..> UC_ManageUserAccount: <<extend>>
    UC_LockUserAccount ..> UC_ManageUserAccount: <<extend>>

    ' Quan hệ <<include>> (các chức năng cần đăng nhập)
    UC_ManageUserAccount ..> UC_Login: <<include>>

    ' Admin
    Admin --> UC_Login
}