@startuml Sơ Đồ Usecase Chi Tiết Admin
left to right direction

' Actor
actor "Quản trị viên" as Admin

rectangle "Quản lý báo cáo vi phạm" {
    ' Use Case cho mọi người (chưa đăng nhập)
    (Đăng nhập) as UC_Login

    ' Use case của Admin
    (Quản lý báo cáo vi phạm) as UC_ManageReport
    (Xem danh sách và tìm kiếm báo cáo vi phạm) as UC_ViewSearchReports
    (Ẩn bài hát vi phạm) as UC_HideReportedSongs
    (Cảnh cáo người dùng) as UC_WarnUser
    (Bỏ qua vi phạm) as UC_DismissReport

    ' Use case cho tất cả Actor
    (Đăng xuất) as UC_Logout

    ' -- Mối quan hệ --
    ' Quan hệ <<extend>>
    ' Xử lý báo cáo vi phạm
    UC_ViewSearchReports ..> UC_ManageReport: <<extend>>
    UC_HideReportedSongs ..> UC_ManageReport: <<extend>>
    UC_WarnUser ..> UC_ManageReport: <<extend>>
    UC_DismissReport ..> UC_ManageReport: <<extend>>

    ' Quan hệ <<include>> (các chức năng cần đăng nhập)
    UC_ManageReport ..> UC_Login : <<include>>

    ' Admin
    Admin --> UC_Login
    Admin --> UC_Logout
}