@startuml Sơ Đồ Usecase Tổng Quát
left to right direction

' Actor
actor "Người dùng" as User
actor "Nghệ sĩ" as Artist
actor "Quản trị viên" as Admin

' Sử dụng kế thừa cho Actor: Nghệ sĩ LÀ MỘT Người dùng
Artist --|> User

rectangle "Hệ thống nghe nhạc trực tuyến" {
  ' Use Case cho mọi người (chưa đăng nhập)
  (Xem danh sách và tìm kiếm bài hát) as UC_ViewSearchSongs
  (Xem và tìm kiếm danh sách nghệ sĩ) as UC_ViewSearchArtist
  (Nghe nhạc) as UC_Play
  (Đăng ký tài khoản) as UC_Register
  (Đăng nhập tài khoản) as UC_Login
  (Quên mật khẩu) as UC_ForgetPassword

  ' Use case cần đăng nhập (cho User và Artist)
  (Quản lý hồ sơ cá nhân) as UC_ManageProfile
  (Quản lý Playlist cá nhân) as UC_ManagePlaylist
  (Quản lý tương tác bài hát) as UC_ManageInteract
  (Theo dõi nghệ sĩ) as UC_Follow
  (Báo cáo vi phạm) as UC_Report

  ' Use case chỉ dành cho Artist
  (Quản lý bài hát cá nhân nghệ sĩ) as UC_ManageSongs

  ' Use case của Admin
  (Xử lý báo cáo vi phạm) as UC_HandleReport
  (Quản lý tài khoản người dùng) as UC_ManageUserAccount

  ' Use case cho tất cả Actor
  (Đăng xuất) as UC_Logout

  ' -- Mối quan hệ --
  ' Quan hệ <<extend>>
  UC_ForgetPassword --> UC_Login : <<extend>>

  ' Quan hệ <<include>> (các chức năng cần đăng nhập)
  UC_ManageProfile --> UC_Login : <<include>>
  UC_ManagePlaylist --> UC_Login: <<include>>
  UC_ManageInteract --> UC_Login: <<include>>
  UC_Follow --> UC_Login : <<include>>
  UC_Report --> UC_Login : <<include>>
  UC_ManageSongs --> UC_Login : <<include>>
  UC_HandleReport --> UC_Login: <<include>>
  UC_ManageUserAccount --> UC_Login: <<include>>

  ' -- Gán các actor --
  ' Actor chưa đăng nhập cũng có thể xem và nghe
  User --> UC_ViewSearchSongs
  User --> UC_Play
  User --> UC_Register
  User --> UC_Login
  User --> UC_ViewSearchArtist

  ' User đã đăng nhập (Artist cũng có thể làm vì kế thừa)
  User --> UC_ManageProfile
  User --> UC_ManagePlaylist
  User --> UC_ManageInteract
  User --> UC_Follow
  User --> UC_Report
  User --> UC_Logout

  ' Artist (chức năng riêng)
  Artist --> UC_ManageSongs

  ' Admin
  Admin --> UC_Play
  Admin --> UC_Login
  Admin --> UC_HandleReport
  Admin --> UC_ManageUserAccount
  Admin --> UC_ViewSearchSongs
  Admin --> UC_ViewSearchArtist
  Admin --> UC_Logout
}
@enduml