@startmindmap BFD
title Sơ đồ phân rã chức năng (BFD) - Hệ thống nghe nhạc trực tuyến

*[#lightgreen] **Hệ thống Nghe nhạc Trực tuyến**
** Chức năng Khám phá
*** Khám phá bài hát
**** Xem danh sách và tìm kiếm bài hát
**** Thích bài hát
**** Bình luận bài hát
**** Chia sẻ bài hát
**** Đăng lại bài hát
**** Nghe nhạc
**** Báo cáo vi phạm
*** Khám phá nghệ sĩ
**** Xem và tìm kiếm danh sách nghệ sĩ
**** Theo dõi Nghệ sĩ
** Chức năng Tài khoản
*** Đăng ký
*** Đăng nhập
*** Đăng xuất
*** Quên mật khẩu
** Chức năng Người dùng
*** Quản lý thư viện cá nhân
**** Xem danh sách và tìm kiếm bài hát yêu thích
**** Xem danh sách và tìm kiếm Follower
**** Xem danh sách và tìm kiếm Following
**** Xem và tìm kiếm lịch sử nghe nhạc
*** Quản lý hồ sơ cá nhân
**** Xem hồ sơ cá nhân
**** Sửa hồ sơ cá nhân
**** Xem danh sách và tìm kiếm bài hát đăng lại
*** Quản lý Playlist cá nhân
**** Xem danh sách và tìm kiếm Playlist cá nhân
**** Tạo Playlist cá nhân
**** Xóa Playlist cá nhân
**** Quản lý chi tiết Playlist cá nhân
***** Xem danh sách và tìm kiếm bài hát trong Playlist
***** Sửa thông tin Playlist
***** Thêm bài hát
***** Xóa bài hát
*** Quản lý bài hát cá nhân
**** Xem danh sách và tìm kiếm bài hát đã tải lên
**** Tải lên bài hát
**** Sửa thông tin bài hát
**** Ẩn bài hát
*** Cài đặt
**** Sửa tài khoản cá nhân
** Chức năng Quản trị
*** Xem tổng quan hệ thống
*** Quản lý tài khoản người dùng
**** Xem danh sách và tìm kiếm tài khoản người dùng
**** Khoá/Mở tài khoản người dùng
*** Quản lý bài hát hệ thống
**** Xem danh sách và tìm kiếm bài hát
**** Ẩn/Hiện bài hát
*** Quản lý báo cáo vi phạm
**** Xem danh sách và tìm kiếm báo cáo vi phạm
**** Ẩn bài hát vi phạm
**** Gửi cảnh cáo người dùng
**** Bỏ qua báo cáo

@endmindmap